/**
 * Regenerates CREDITS.md and src/generated/sources.json from
 * public/textures/manifest.json and public/data/README.md files.
 *   npm run credits
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

interface Entry { id: string; source: { title: string; url: string }; license: { spdx: string; url?: string }; attribution: string; transforms?: string }
const manifest = JSON.parse(readFileSync('public/textures/manifest.json', 'utf8')) as { textures: Entry[] };

const dataSets: { id: string; title: string; readme: string }[] = [];
for (const dir of readdirSync('public/data')) {
  const readme = join('public/data', dir, 'README.md');
  if (existsSync(readme)) {
    const text = readFileSync(readme, 'utf8');
    dataSets.push({ id: dir, title: text.split('\n')[0]!.replace(/^#\s*/, ''), readme: text });
  }
}

// No timestamp here on purpose: the data-refresh workflow must produce an empty diff on a no-change day.
const sources = {
  textures: manifest.textures.map((t) => ({ id: t.id, title: t.source.title, url: t.source.url, license: t.license.spdx, licenseUrl: t.license.url ?? '', attribution: t.attribution })),
  data: dataSets.map((d) => ({ id: d.id, title: d.title, summary: d.readme.split('\n').slice(1).join('\n').trim().slice(0, 600) })),
  software: [
    { title: 'astronomy-engine (VSOP87 / ELP-2000 ephemerides)', url: 'https://github.com/cosinekitty/astronomy', license: 'MIT' },
    { title: 'three.js', url: 'https://threejs.org', license: 'MIT' },
    { title: 'postprocessing', url: 'https://github.com/pmndrs/postprocessing', license: 'zlib' },
    { title: 'satellite.js (SGP4)', url: 'https://github.com/shashwatak/satellite-js', license: 'MIT' },
  ],
};
mkdirSync('src/generated', { recursive: true });
writeFileSync('src/generated/sources.json', JSON.stringify(sources, null, 1));

const byLicense = new Map<string, Entry[]>();
for (const t of manifest.textures) byLicense.set(t.license.spdx, [...(byLicense.get(t.license.spdx) ?? []), t]);

let md = `# Credits\n\nEvery dataset and texture in \`public/\` is listed here with its source and license.\nGenerated by \`npm run credits\` from \`public/textures/manifest.json\` and the README in each \`public/data/*\` folder.\n\n## Data\n\n`;
for (const d of dataSets) md += `### ${d.title}\n\n${d.readme.split('\n').slice(1).join('\n').trim()}\n\n`;
md += `## Textures\n\n| Texture | Source | License | Transforms |\n| --- | --- | --- | --- |\n`;
for (const t of manifest.textures) md += `| ${t.id} | [${t.source.title}](${t.source.url}) | ${t.license.spdx} | ${t.transforms ?? ''} |\n`;
md += `\nAttribution: ${[...new Set(manifest.textures.map((t) => t.attribution))].join('; ')}.\n\n## Software\n\n`;
for (const s of sources.software) md += `- [${s.title}](${s.url}), ${s.license}\n`;
md += `\n## Inspiration\n\nSee THIRD_PARTY_NOTICES.md for the MIT-licensed project whose feature set inspired this one.\n`;
writeFileSync('CREDITS.md', md);
console.log(`credits: ${manifest.textures.length} textures, ${dataSets.length} datasets`);
